url: https://www.andjosh.com
author: Josh Beckman
email: email@andjosh.com
title: Josh
photos_link: https://www.instagram.com/photos.andjosh/

collections:
  lists:
    output: true
  charts:
    output: true
  decks:
    output: true

permalink: pretty
markdown: kramdown
