url: https://www.andjosh.com
baseurl: /
author: Josh Beckman
email: email@andjosh.com
title: Josh
tagline: 'A Jekyll theme'
description: 'Founder of <a href="https://www.narro.co" target="_blank">Narro</a>. Leading the product & engineering team at <a href="https://www.officeluv.com" target="_blank">OfficeLuv</a>.'

collections:
  lists:
    output: true
  charts:
    output: true
  decks:
    output: true

links:
  - title: About
    url: /about/
  - title: Talks
    url: /presents/
  - title: Newsletter
    url: /newsletter/
  - title: RSS
    url: /rss.xml

markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 20
paginate_path: '/page:num'

plugins: [jekyll-paginate]

# data
headers:
  - Josh
prose:
  media: 'images'
