url: http://andjosh.com
author: Josh
email: email@andjosh.com
title: andjosh

collections:
  fictions:
    output: true
  photos:
    output: true
  lists:
    output: true
  graphs:
    output: true

permalink: pretty
markdown: redcarpet
