url: https://www.andjosh.com
author: Josh Beckman
email: email@andjosh.com
title: Josh
photos_link: https://www.instagram.com/photos.andjosh/

collections:
  lists:
    output: true
  charts:
    output: true
  decks:
    output: true

markdown: kramdown
permalink: pretty
paginate: 20
paginate_path: '/page:num'

plugins: [jekyll-paginate]

# data
headers:
  - Josh
