---
title: Josh Beckman
timezone: UTC
collections:
  charts:
    title: Charts
    output: true
  decks:
    title: Decks
    output: true
  lists:
    title: Lists
    output: true
  my_tags:
    title: My Tags
    output: true
    permalink: "/tags/:name/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: my_tags
  values:
    layout: tag
url: https://www.joshbeckman.org
baseurl: ''
author:
  name: Josh Beckman
  url: https://www.joshbeckman.org
  email: josh@joshbeckman.org
tagline: Director of Engineering
description: Founder of <a href="https://www.narro.co" target="_blank">Narro</a>.
  Leading the product & engineering team at <a href="https://www.officeluv.com" target="_blank">OfficeLuv</a>.
links:
- title: Posts
  url: "/posts/"
- title: Talks
  url: "/presents/"
- title: Newsletter
  url: "/newsletter/"
- title: RSS
  url: "/rss.xml"
- title: Contact
  url: "/contact/"
markdown: kramdown
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
highlighter: rouge
permalink: pretty
paginate: 20
paginate_path: "/posts/page:num/"
plugins:
- jekyll-paginate
headers:
- Josh
prose:
  media: images
blogroll:
  - title: Charity Majors
    url: https://charity.wtf
  - title: Christine Dodrill
    url: https://christine.website/blog
  - title: Grumpy Website
    url: https://grumpy.website
  - title: High Scalability
    url: http://highscalability.com/blog/
  - title: Nadia Eghbal
    url: https://nadiaeghbal.com
  - title: Simon Eskildsen
    url: https://sirupsen.com
  - title: Indexed
    url: https://thisisindexed.com
  - title: Fred Hebert
    url: https://ferd.ca
  - title: Jenn Schiffer
    url: https://livelaugh.blog
  - title: Rachel By the Bay
    url: https://rachelbythebay.com/w/
  - title: Brent Simmons
    url: https://inessential.com
  - title: Dan Luu
    url: https://danluu.com
  - title: Maciej Cegłowski
    url: //idlewords.com
  - title: Marco Arment
    url: //marco.org
