url: https://www.andjosh.com
baseurl: ''
author: Josh Beckman
email: email@andjosh.com
title: Josh
tagline: 'A Jekyll theme'
description: 'Founder of <a href="https://www.narro.co" target="_blank">Narro</a>. Leading the product & engineering team at <a href="https://www.officeluv.com" target="_blank">OfficeLuv</a>.'

collections:
  my_tags:
    output: true
    permalink: /tags/:name/
  lists:
    output: true
  charts:
    output: true
  decks:
    output: true

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: tag

links:
  - title: Posts
    url: /posts/
  - title: Talks
    url: /presents/
  - title: Newsletter
    url: /newsletter/
  - title: RSS
    url: /rss.xml
  - title: Contact
    url: /contact/

markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 20
paginate_path: '/posts/page:num/'

plugins: [jekyll-paginate]

# data
headers:
  - Josh
prose:
  media: 'images'
